# trivial cmake project file to enable debugging in clion
# currently far from perfect and can't really be used to build the project (use qmake to build)
# but it can be used as starting point for clion to recognise at least some parts of Qt
# I'll improve later

# additional options to be set before use:
# EXAMPLE:
# cmake flags:
# -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/d/dev/Qt/5.5/gcc_64;/d/dev/libs
# environment:
# PKG_CONFIG_PATH=/d/dev/libs/lib/pkgconfig
# where in example "/d/dev/libs" is path where additional libs are installed (e.g. tidy)
# and "/d/dev/Qt/5.5/gcc_64" is example of QT root

cmake_minimum_required (VERSION 3.0.2)
project (nixnote2)
add_definitions(-std=c++17)

find_package (Qt5Widgets REQUIRED)
find_package (Qt5Gui REQUIRED)
find_package (Qt5Sql REQUIRED)
find_package (Qt5Network REQUIRED)
find_package (Qt5WebKit REQUIRED)
find_package (Qt5WebKitWidgets REQUIRED)

find_package(PkgConfig REQUIRED)
pkg_check_modules(TIDY REQUIRED tidy)

set (nixnote2_src
        src/application.cpp
        src/global.cpp
        src/main.cpp
        src/nixnote.cpp
        src/cmdtools/addnote.cpp
        src/cmdtools/alternote.cpp
        src/cmdtools/cmdlinequery.cpp
        src/cmdtools/cmdlinetool.cpp
        src/cmdtools/deletenote.cpp
        src/cmdtools/emailnote.cpp
        src/cmdtools/extractnotes.cpp
        src/cmdtools/extractnotetext.cpp
        src/cmdtools/importnotes.cpp
        src/cmdtools/signalgui.cpp
        src/communication/communicationerror.cpp
        src/communication/communicationmanager.cpp
        src/dialog/aboutdialog.cpp
        src/dialog/accountdialog.cpp
        src/dialog/accountmaintenancedialog.cpp
        src/dialog/adduseraccountdialog.cpp
        src/dialog/closenotebookdialog.cpp
        src/dialog/databasestatus.cpp
        src/dialog/emaildialog.cpp
        src/dialog/encryptdialog.cpp
        src/dialog/endecryptdialog.cpp
        src/dialog/faderdialog.cpp
        src/dialog/htmlentitiesdialog.cpp
        src/dialog/insertlatexdialog.cpp
        src/dialog/insertlinkdialog.cpp
        src/dialog/locationdialog.cpp
        src/dialog/logindialog.cpp
        src/dialog/notebookproperties.cpp
        src/dialog/notehistoryselect.cpp
        src/dialog/noteproperties.cpp
        src/dialog/preferences/appearancepreferences.cpp
        src/dialog/preferences/debugpreferences.cpp
        src/dialog/preferences/emailpreferences.cpp
        src/dialog/preferences/exitpreferences.cpp
        src/dialog/preferences/localepreferences.cpp
        src/dialog/preferences/preferencesdialog.cpp
        src/dialog/preferences/searchpreferences.cpp
        src/dialog/preferences/syncpreferences.cpp
        src/dialog/preferences/thumbnailpreferences.cpp
        src/dialog/remindersetdialog.cpp
        src/dialog/savedsearchproperties.cpp
        src/dialog/shortcutdialog.cpp
        src/dialog/spellcheckdialog.cpp
        src/dialog/tabledialog.cpp
        src/dialog/tagproperties.cpp
        src/dialog/watchfolderadd.cpp
        src/dialog/watchfolderdialog.cpp
        src/email/emailaddress.cpp
        src/email/mimeattachment.cpp
        src/email/mimecontentformatter.cpp
        src/email/mimefile.cpp
        src/email/mimehtml.cpp
        src/email/mimeinlinefile.cpp
        src/email/mimemessage.cpp
        src/email/mimemultipart.cpp
        src/email/mimepart.cpp
        src/email/mimetext.cpp
        src/email/quotedprintable.cpp
        src/email/smtpclient.cpp
        src/exits/exitmanager.cpp
        src/exits/exitpoint.cpp
        src/filters/filtercriteria.cpp
        src/filters/filterengine.cpp
        src/filters/notesortfilterproxymodel.cpp
        src/filters/remotequery.cpp
        src/gui/browserWidgets/authoreditor.cpp
        src/gui/browserWidgets/colormenu.cpp
        src/gui/browserWidgets/dateeditor.cpp
        src/gui/browserWidgets/datetimeeditor.cpp
        src/gui/browserWidgets/editorbuttonbar.cpp
        src/gui/browserWidgets/expandbutton.cpp
        src/gui/browserWidgets/fontnamecombobox.cpp
        src/gui/browserWidgets/fontsizecombobox.cpp
        src/gui/browserWidgets/locationeditor.cpp
        src/gui/browserWidgets/notebookmenubutton.cpp
        src/gui/browserWidgets/ntitleeditor.cpp
        src/gui/browserWidgets/reminderbutton.cpp
        src/gui/browserWidgets/table/tablepropertiesdialog.cpp
        src/gui/browserWidgets/tageditor.cpp
        src/gui/browserWidgets/tageditornewtag.cpp
        src/gui/browserWidgets/tagviewer.cpp
        src/gui/browserWidgets/urleditor.cpp
        src/gui/datedelegate.cpp
        src/gui/externalbrowse.cpp
        src/gui/favoritesview.cpp
        src/gui/favoritesviewdelegate.cpp
        src/gui/favoritesviewitem.cpp
        src/gui/findreplace.cpp
        src/gui/flowlayout.cpp
        src/gui/imagedelegate.cpp
        src/gui/lineedit.cpp
        src/gui/nattributetree.cpp
        src/gui/nbrowserwindow.cpp
        src/gui/nmainmenubar.cpp
        src/gui/nnotebookview.cpp
        src/gui/nnotebookviewdelegate.cpp
        src/gui/nnotebookviewitem.cpp
        src/gui/nsearchview.cpp
        src/gui/nsearchviewitem.cpp
        src/gui/ntableview.cpp
        src/gui/ntableviewheader.cpp
        src/gui/ntabwidget.cpp
        src/gui/ntagview.cpp
        src/gui/ntagviewdelegate.cpp
        src/gui/ntagviewitem.cpp
        src/gui/ntrashtree.cpp
        src/gui/ntrashviewdelegate.cpp
        src/gui/numberdelegate.cpp
        src/gui/nwebpage.cpp
        src/gui/nwebview.cpp
        src/gui/plugins/pluginfactory.cpp
        src/gui/plugins/popplergraphicsview.cpp
        src/gui/plugins/popplerviewer.cpp
        src/gui/reminderorderdelegate.cpp
        src/gui/shortcutkeys.cpp
        src/gui/traymenu.cpp
        src/gui/treewidgeteditor.cpp
        src/gui/truefalsedelegate.cpp
        src/gui/widgetpanel.cpp
        src/logger/qsdebugoutput.cpp
        src/logger/qslog.cpp
        src/logger/qslogdest.cpp
        src/models/notecache.cpp
        src/models/notemodel.cpp
        src/models/ntreemodel.cpp
        src/oauth/oauthtokenizer.cpp
        src/hunspell/spellchecker.cpp
        src/qevercloud/src/DurableService.cpp
        src/qevercloud/src/EventLoopFinisher.cpp
        src/qevercloud/src/Http.cpp
        src/qevercloud/src/HttpRequestParser.cpp
        src/qevercloud/src/HttpUtils.cpp
        src/qevercloud/src/IInkNoteImageDownloader.cpp
        src/qevercloud/src/INoteThumbnailDownloader.cpp
        src/qevercloud/src/Impl.cpp
        src/qevercloud/src/InkNoteImageDownloader.cpp
        src/qevercloud/src/IRequestContext.cpp
        src/qevercloud/src/Log.cpp
        src/qevercloud/src/NetworkProxy.cpp
        src/qevercloud/src/NetworkReplyFetcher.cpp
        src/qevercloud/src/NoteThumbnailDownloader.cpp
        src/qevercloud/src/NoteThumbnailDownloader.h
        src/qevercloud/src/Printable.cpp
        src/qevercloud/src/RequestContext.cpp
        src/qevercloud/src/RequestContextBuilder.cpp
        src/qevercloud/src/VersionInfo.cpp
        src/qevercloud/src/Constants.cpp
        src/qevercloud/src/EDAMErrorCode.cpp
        src/qevercloud/src/exceptions/EDAMInvalidContactsException.cpp
        src/qevercloud/src/exceptions/EDAMNotFoundException.cpp
        src/qevercloud/src/exceptions/EDAMSystemException.cpp
        src/qevercloud/src/exceptions/EDAMSystemExceptionAuthExpired.cpp
        src/qevercloud/src/exceptions/EDAMSystemExceptionRateLimitReached.cpp
        src/qevercloud/src/exceptions/EDAMUserException.cpp
        src/qevercloud/src/exceptions/EverCloudException.cpp
        src/qevercloud/src/exceptions/EvernoteException.cpp
        src/qevercloud/src/exceptions/NetworkException.cpp
        src/qevercloud/src/exceptions/ThriftException.cpp
        src/qevercloud/src/exceptions/impl/EDAMInvalidContactsExceptionImpl.cpp
        src/qevercloud/src/exceptions/impl/EDAMNotFoundExceptionImpl.cpp
        src/qevercloud/src/exceptions/impl/EDAMSystemExceptionImpl.cpp
        src/qevercloud/src/exceptions/impl/EDAMUserExceptionImpl.cpp
        src/qevercloud/src/serialization/json/Accounting.cpp
        src/qevercloud/src/serialization/json/AccountLimits.cpp
        src/qevercloud/src/serialization/json/AuthenticationResult.cpp
        src/qevercloud/src/serialization/json/BootstrapInfo.cpp
        src/qevercloud/src/serialization/json/BootstrapProfile.cpp
        src/qevercloud/src/serialization/json/BootstrapSettings.cpp
        src/qevercloud/src/serialization/json/BusinessInvitation.cpp
        src/qevercloud/src/serialization/json/BusinessNotebook.cpp
        src/qevercloud/src/serialization/json/BusinessUserAttributes.cpp
        src/qevercloud/src/serialization/json/BusinessUserInfo.cpp
        src/qevercloud/src/serialization/json/CanMoveToContainerRestrictions.cpp
        src/qevercloud/src/serialization/json/Contact.cpp
        src/qevercloud/src/serialization/json/CreateOrUpdateNotebookSharesResult.cpp
        src/qevercloud/src/serialization/json/Data.cpp
        src/qevercloud/src/serialization/json/EDAMInvalidContactsException.cpp
        src/qevercloud/src/serialization/json/EDAMNotFoundException.cpp
        src/qevercloud/src/serialization/json/EDAMSystemException.cpp
        src/qevercloud/src/serialization/json/EDAMUserException.cpp
        src/qevercloud/src/serialization/json/Identity.cpp
        src/qevercloud/src/serialization/json/InvitationShareRelationship.cpp
        src/qevercloud/src/serialization/json/LazyMap.cpp
        src/qevercloud/src/serialization/json/LinkedNotebook.cpp
        src/qevercloud/src/serialization/json/ManageNotebookSharesError.cpp
        src/qevercloud/src/serialization/json/ManageNotebookSharesParameters.cpp
        src/qevercloud/src/serialization/json/ManageNotebookSharesResult.cpp
        src/qevercloud/src/serialization/json/ManageNoteSharesError.cpp
        src/qevercloud/src/serialization/json/ManageNoteSharesParameters.cpp
        src/qevercloud/src/serialization/json/ManageNoteSharesResult.cpp
        src/qevercloud/src/serialization/json/MemberShareRelationship.cpp
        src/qevercloud/src/serialization/json/Note.cpp
        src/qevercloud/src/serialization/json/NoteAttributes.cpp
        src/qevercloud/src/serialization/json/Notebook.cpp
        src/qevercloud/src/serialization/json/NotebookDescriptor.cpp
        src/qevercloud/src/serialization/json/NotebookRecipientSettings.cpp
        src/qevercloud/src/serialization/json/NotebookRestrictions.cpp
        src/qevercloud/src/serialization/json/NotebookShareTemplate.cpp
        src/qevercloud/src/serialization/json/NoteCollectionCounts.cpp
        src/qevercloud/src/serialization/json/NoteEmailParameters.cpp
        src/qevercloud/src/serialization/json/NoteFilter.cpp
        src/qevercloud/src/serialization/json/NoteInvitationShareRelationship.cpp
        src/qevercloud/src/serialization/json/NoteLimits.cpp
        src/qevercloud/src/serialization/json/NoteList.cpp
        src/qevercloud/src/serialization/json/NoteMemberShareRelationship.cpp
        src/qevercloud/src/serialization/json/NoteMetadata.cpp
        src/qevercloud/src/serialization/json/NoteRestrictions.cpp
        src/qevercloud/src/serialization/json/NoteResultSpec.cpp
        src/qevercloud/src/serialization/json/NoteShareRelationshipRestrictions.cpp
        src/qevercloud/src/serialization/json/NoteShareRelationships.cpp
        src/qevercloud/src/serialization/json/NotesMetadataList.cpp
        src/qevercloud/src/serialization/json/NotesMetadataResultSpec.cpp
        src/qevercloud/src/serialization/json/NoteVersionId.cpp
        src/qevercloud/src/serialization/json/PublicUserInfo.cpp
        src/qevercloud/src/serialization/json/Publishing.cpp
        src/qevercloud/src/serialization/json/RelatedContent.cpp
        src/qevercloud/src/serialization/json/RelatedContentImage.cpp
        src/qevercloud/src/serialization/json/RelatedQuery.cpp
        src/qevercloud/src/serialization/json/RelatedResult.cpp
        src/qevercloud/src/serialization/json/RelatedResultSpec.cpp
        src/qevercloud/src/serialization/json/Resource.cpp
        src/qevercloud/src/serialization/json/ResourceAttributes.cpp
        src/qevercloud/src/serialization/json/SavedSearch.cpp
        src/qevercloud/src/serialization/json/SavedSearchScope.cpp
        src/qevercloud/src/serialization/json/SharedNote.cpp
        src/qevercloud/src/serialization/json/SharedNotebook.cpp
        src/qevercloud/src/serialization/json/SharedNotebookRecipientSettings.cpp
        src/qevercloud/src/serialization/json/SharedNoteTemplate.cpp
        src/qevercloud/src/serialization/json/ShareRelationshipRestrictions.cpp
        src/qevercloud/src/serialization/json/ShareRelationships.cpp
        src/qevercloud/src/serialization/json/SyncChunk.cpp
        src/qevercloud/src/serialization/json/SyncChunkFilter.cpp
        src/qevercloud/src/serialization/json/SyncState.cpp
        src/qevercloud/src/serialization/json/Tag.cpp
        src/qevercloud/src/serialization/json/UpdateNoteIfUsnMatchesResult.cpp
        src/qevercloud/src/serialization/json/User.cpp
        src/qevercloud/src/serialization/json/UserAttributes.cpp
        src/qevercloud/src/serialization/json/UserIdentity.cpp
        src/qevercloud/src/serialization/json/UserProfile.cpp
        src/qevercloud/src/serialization/json/UserUrls.cpp
        src/qevercloud/src/services/NoteStore.cpp
        src/qevercloud/src/services/NoteStoreServer.cpp
        src/qevercloud/src/services/UserStore.cpp
        src/qevercloud/src/services/UserStoreServer.cpp
        src/qevercloud/src/types/Accounting.cpp
        src/qevercloud/src/types/AccountLimits.cpp
        src/qevercloud/src/types/AuthenticationResult.cpp
        src/qevercloud/src/types/BootstrapInfo.cpp
        src/qevercloud/src/types/BootstrapProfile.cpp
        src/qevercloud/src/types/BootstrapSettings.cpp
        src/qevercloud/src/types/BusinessInvitation.cpp
        src/qevercloud/src/types/BusinessNotebook.cpp
        src/qevercloud/src/types/BusinessUserAttributes.cpp
        src/qevercloud/src/types/BusinessUserInfo.cpp
        src/qevercloud/src/types/CanMoveToContainerRestrictions.cpp
        src/qevercloud/src/types/Contact.cpp
        src/qevercloud/src/types/CreateOrUpdateNotebookSharesResult.cpp
        src/qevercloud/src/types/Data.cpp
        src/qevercloud/src/types/Identity.cpp
        src/qevercloud/src/types/InvitationShareRelationship.cpp
        src/qevercloud/src/types/LazyMap.cpp
        src/qevercloud/src/types/LinkedNotebook.cpp
        src/qevercloud/src/types/ManageNotebookSharesError.cpp
        src/qevercloud/src/types/ManageNotebookSharesParameters.cpp
        src/qevercloud/src/types/ManageNotebookSharesResult.cpp
        src/qevercloud/src/types/ManageNoteSharesError.cpp
        src/qevercloud/src/types/ManageNoteSharesParameters.cpp
        src/qevercloud/src/types/ManageNoteSharesResult.cpp
        src/qevercloud/src/types/MemberShareRelationship.cpp
        src/qevercloud/src/types/Metatypes.cpp
        src/qevercloud/src/types/Note.cpp
        src/qevercloud/src/types/NoteAttributes.cpp
        src/qevercloud/src/types/Notebook.cpp
        src/qevercloud/src/types/NotebookDescriptor.cpp
        src/qevercloud/src/types/NotebookRecipientSettings.cpp
        src/qevercloud/src/types/NotebookRestrictions.cpp
        src/qevercloud/src/types/NotebookShareTemplate.cpp
        src/qevercloud/src/types/NoteCollectionCounts.cpp
        src/qevercloud/src/types/NoteEmailParameters.cpp
        src/qevercloud/src/types/NoteFilter.cpp
        src/qevercloud/src/types/NoteInvitationShareRelationship.cpp
        src/qevercloud/src/types/NoteLimits.cpp
        src/qevercloud/src/types/NoteList.cpp
        src/qevercloud/src/types/NoteMemberShareRelationship.cpp
        src/qevercloud/src/types/NoteMetadata.cpp
        src/qevercloud/src/types/NoteRestrictions.cpp
        src/qevercloud/src/types/NoteResultSpec.cpp
        src/qevercloud/src/types/NoteShareRelationshipRestrictions.cpp
        src/qevercloud/src/types/NoteShareRelationships.cpp
        src/qevercloud/src/types/NotesMetadataList.cpp
        src/qevercloud/src/types/NotesMetadataResultSpec.cpp
        src/qevercloud/src/types/NoteVersionId.cpp
        src/qevercloud/src/types/PublicUserInfo.cpp
        src/qevercloud/src/types/Publishing.cpp
        src/qevercloud/src/types/RelatedContent.cpp
        src/qevercloud/src/types/RelatedContentImage.cpp
        src/qevercloud/src/types/RelatedQuery.cpp
        src/qevercloud/src/types/RelatedResult.cpp
        src/qevercloud/src/types/RelatedResultSpec.cpp
        src/qevercloud/src/types/Resource.cpp
        src/qevercloud/src/types/ResourceAttributes.cpp
        src/qevercloud/src/types/SavedSearch.cpp
        src/qevercloud/src/types/SavedSearchScope.cpp
        src/qevercloud/src/types/SharedNote.cpp
        src/qevercloud/src/types/SharedNotebook.cpp
        src/qevercloud/src/types/SharedNotebookRecipientSettings.cpp
        src/qevercloud/src/types/SharedNoteTemplate.cpp
        src/qevercloud/src/types/ShareRelationshipRestrictions.cpp
        src/qevercloud/src/types/ShareRelationships.cpp
        src/qevercloud/src/types/SyncChunk.cpp
        src/qevercloud/src/types/SyncChunkFilter.cpp
        src/qevercloud/src/types/SyncState.cpp
        src/qevercloud/src/types/Tag.cpp
        src/qevercloud/src/types/Types_io.cpp
        src/qevercloud/src/types/UpdateNoteIfUsnMatchesResult.cpp
        src/qevercloud/src/types/User.cpp
        src/qevercloud/src/types/UserAttributes.cpp
        src/qevercloud/src/types/UserIdentity.cpp
        src/qevercloud/src/types/UserProfile.cpp
        src/qevercloud/src/types/UserUrls.cpp
        src/qevercloud/src/types/impl/AccountingImpl.cpp
        src/qevercloud/src/types/impl/AccountLimitsImpl.cpp
        src/qevercloud/src/types/impl/AuthenticationResultImpl.cpp
        src/qevercloud/src/types/impl/BootstrapInfoImpl.cpp
        src/qevercloud/src/types/impl/BootstrapProfileImpl.cpp
        src/qevercloud/src/types/impl/BootstrapSettingsImpl.cpp
        src/qevercloud/src/types/impl/BusinessInvitationImpl.cpp
        src/qevercloud/src/types/impl/BusinessNotebookImpl.cpp
        src/qevercloud/src/types/impl/BusinessUserAttributesImpl.cpp
        src/qevercloud/src/types/impl/BusinessUserInfoImpl.cpp
        src/qevercloud/src/types/impl/CanMoveToContainerRestrictionsImpl.cpp
        src/qevercloud/src/types/impl/ContactImpl.cpp
        src/qevercloud/src/types/impl/CreateOrUpdateNotebookSharesResultImpl.cpp
        src/qevercloud/src/types/impl/DataImpl.cpp
        src/qevercloud/src/types/impl/IdentityImpl.cpp
        src/qevercloud/src/types/impl/InvitationShareRelationshipImpl.cpp
        src/qevercloud/src/types/impl/LazyMapImpl.cpp
        src/qevercloud/src/types/impl/LinkedNotebookImpl.cpp
        src/qevercloud/src/types/impl/ManageNotebookSharesErrorImpl.cpp
        src/qevercloud/src/types/impl/ManageNotebookSharesParametersImpl.cpp
        src/qevercloud/src/types/impl/ManageNotebookSharesResultImpl.cpp
        src/qevercloud/src/types/impl/ManageNoteSharesErrorImpl.cpp
        src/qevercloud/src/types/impl/ManageNoteSharesParametersImpl.cpp
        src/qevercloud/src/types/impl/ManageNoteSharesResultImpl.cpp
        src/qevercloud/src/types/impl/MemberShareRelationshipImpl.cpp
        src/qevercloud/src/types/impl/NoteAttributesImpl.cpp
        src/qevercloud/src/types/impl/NotebookImpl.cpp
        src/qevercloud/src/types/impl/NotebookDescriptorImpl.cpp
        src/qevercloud/src/types/impl/NotebookRecipientSettingsImpl.cpp
        src/qevercloud/src/types/impl/NotebookRestrictionsImpl.cpp
        src/qevercloud/src/types/impl/NotebookShareTemplateImpl.cpp
        src/qevercloud/src/types/impl/NoteCollectionCountsImpl.cpp
        src/qevercloud/src/types/impl/NoteImpl.cpp
        src/qevercloud/src/types/impl/NoteEmailParametersImpl.cpp
        src/qevercloud/src/types/impl/NoteFilterImpl.cpp
        src/qevercloud/src/types/impl/NoteInvitationShareRelationshipImpl.cpp
        src/qevercloud/src/types/impl/NoteLimitsImpl.cpp
        src/qevercloud/src/types/impl/NoteListImpl.cpp
        src/qevercloud/src/types/impl/NoteMemberShareRelationshipImpl.cpp
        src/qevercloud/src/types/impl/NoteMetadataImpl.cpp
        src/qevercloud/src/types/impl/NoteRestrictionsImpl.cpp
        src/qevercloud/src/types/impl/NoteResultSpecImpl.cpp
        src/qevercloud/src/types/impl/NoteShareRelationshipRestrictionsImpl.cpp
        src/qevercloud/src/types/impl/NoteShareRelationshipsImpl.cpp
        src/qevercloud/src/types/impl/NotesMetadataListImpl.cpp
        src/qevercloud/src/types/impl/NotesMetadataResultSpecImpl.cpp
        src/qevercloud/src/types/impl/NoteVersionIdImpl.cpp
        src/qevercloud/src/types/impl/PublicUserInfoImpl.cpp
        src/qevercloud/src/types/impl/PublishingImpl.cpp
        src/qevercloud/src/types/impl/RelatedContentImpl.cpp
        src/qevercloud/src/types/impl/RelatedContentImageImpl.cpp
        src/qevercloud/src/types/impl/RelatedQueryImpl.cpp
        src/qevercloud/src/types/impl/RelatedResultImpl.cpp
        src/qevercloud/src/types/impl/RelatedResultSpecImpl.cpp
        src/qevercloud/src/types/impl/ResourceAttributesImpl.cpp
        src/qevercloud/src/types/impl/ResourceImpl.cpp
        src/qevercloud/src/types/impl/SavedSearchImpl.cpp
        src/qevercloud/src/types/impl/SavedSearchScopeImpl.cpp
        src/qevercloud/src/types/impl/SharedNotebookImpl.cpp
        src/qevercloud/src/types/impl/SharedNotebookRecipientSettingsImpl.cpp
        src/qevercloud/src/types/impl/SharedNoteImpl.cpp
        src/qevercloud/src/types/impl/SharedNoteTemplateImpl.cpp
        src/qevercloud/src/types/impl/ShareRelationshipRestrictionsImpl.cpp
        src/qevercloud/src/types/impl/ShareRelationshipsImpl.cpp
        src/qevercloud/src/types/impl/SyncChunkImpl.cpp
        src/qevercloud/src/types/impl/SyncChunkFilterImpl.cpp
        src/qevercloud/src/types/impl/SyncStateImpl.cpp
        src/qevercloud/src/types/impl/TagImpl.cpp
        src/qevercloud/src/types/impl/UpdateNoteIfUsnMatchesResultImpl.cpp
        src/qevercloud/src/types/impl/UserAttributesImpl.cpp
        src/qevercloud/src/types/impl/UserImpl.cpp
        src/qevercloud/src/types/impl/UserIdentityImpl.cpp
        src/qevercloud/src/types/impl/UserProfileImpl.cpp
        src/qevercloud/src/types/impl/UserUrlsImpl.cpp
        src/qevercloud/src/oauth/AbstractOAuthEngine.cpp
        src/qevercloud/src/oauth/OAuth.cpp
        src/qevercloud/src/oauth/Utils.cpp
        src/qevercloud/src/oauth/OAuthSystemBrowser.cpp
        src/reminders/reminderevent.cpp
        src/reminders/remindermanager.cpp
        src/settings/accountsmanager.cpp
        src/settings/colorsettings.cpp
        src/settings/filemanager.cpp
        src/settings/startupconfig.cpp
        src/sql/configstore.cpp
        src/sql/databaseconnection.cpp
        src/sql/databaseupgrade.cpp
        src/sql/datastore.cpp
        src/sql/favoritesrecord.cpp
        src/sql/favoritestable.cpp
        src/sql/filewatchertable.cpp
        src/sql/linkednotebooktable.cpp
        src/sql/notebooktable.cpp
        src/sql/notemetadata.cpp
        src/sql/notetable.cpp
        src/sql/nsqlquery.cpp
        src/sql/resourcetable.cpp
        src/sql/searchtable.cpp
        src/sql/sharednotebooktable.cpp
        src/sql/tagtable.cpp
        src/sql/usertable.cpp
        src/html/attachmenticonbuilder.cpp
        src/html/enmlformatter.cpp
        src/html/noteformatter.cpp
        src/html/tagscanner.cpp
        src/html/thumbnailer.cpp
        src/threads/browserrunner.cpp
        src/threads/counterrunner.cpp
        src/threads/indexrunner.cpp
        src/threads/syncrunner.cpp
        src/utilities/crossmemorymapper.cpp
        src/utilities/debugtool.cpp
        src/utilities/encrypt.cpp
        src/utilities/mimereference.cpp
        src/utilities/noteindexer.cpp
        src/utilities/nuuid.cpp
        src/utilities/pixelconverter.cpp
        src/utilities/NixnoteStringUtils.cpp
        src/watcher/filewatcher.cpp
        src/watcher/filewatchermanager.cpp
        src/xml/batchimport.cpp
        src/xml/exportdata.cpp
        src/xml/importdata.cpp
        src/xml/importenex.cpp
        src/xml/xmlhighlighter.cpp
        src/quentier/utility/StringUtils.cpp
        src/quentier/utility/StringUtils_p.cpp
        testsrc/tests.cpp
)
set (nixnote2_hdr
        src/application.h
        src/nixnote.h
        src/global.h
        src/cmdtools/addnote.h
        src/cmdtools/alternote.h
        src/cmdtools/cmdlinequery.h
        src/cmdtools/cmdlinetool.h
        src/cmdtools/deletenote.h
        src/cmdtools/emailnote.h
        src/cmdtools/extractnotes.h
        src/cmdtools/extractnotetext.h
        src/cmdtools/importnotes.h
        src/cmdtools/signalgui.h
        src/communication/communicationerror.h
        src/communication/communicationmanager.h
        src/dialog/aboutdialog.h
        src/dialog/accountdialog.h
        src/dialog/accountmaintenancedialog.h
        src/dialog/adduseraccountdialog.h
        src/dialog/closenotebookdialog.h
        src/dialog/databasestatus.h
        src/dialog/emaildialog.h
        src/dialog/encryptdialog.h
        src/dialog/endecryptdialog.h
        src/dialog/faderdialog.h
        src/dialog/htmlentitiesdialog.h
        src/dialog/insertlatexdialog.h
        src/dialog/insertlinkdialog.h
        src/dialog/locationdialog.h
        src/dialog/logindialog.h
        src/dialog/notebookproperties.h
        src/dialog/notehistoryselect.h
        src/dialog/noteproperties.h
        src/dialog/preferences/appearancepreferences.h
        src/dialog/preferences/debugpreferences.h
        src/dialog/preferences/emailpreferences.h
        src/dialog/preferences/exitpreferences.h
        src/dialog/preferences/localepreferences.h
        src/dialog/preferences/preferencesdialog.h
        src/dialog/preferences/searchpreferences.h
        src/dialog/preferences/syncpreferences.h
        src/dialog/preferences/thumbnailpreferences.h
        src/dialog/remindersetdialog.h
        src/dialog/savedsearchproperties.h
        src/dialog/shortcutdialog.h
        src/dialog/spellcheckdialog.h
        src/dialog/tabledialog.h
        src/dialog/tagproperties.h
        src/dialog/watchfolderadd.h
        src/dialog/watchfolderdialog.h
        src/email/emailaddress.h
        src/email/mimeattachment.h
        src/email/mimecontentformatter.h
        src/email/mimefile.h
        src/email/mimehtml.h
        src/email/mimeinlinefile.h
        src/email/mimemessage.h
        src/email/mimemultipart.h
        src/email/mimepart.h
        src/email/mimetext.h
        src/email/quotedprintable.h
        src/email/smtpclient.h
        src/email/smtpexports.h
        src/exits/exitmanager.h
        src/exits/exitpoint.h
        src/filters/filtercriteria.h
        src/filters/filterengine.h
        src/filters/notesortfilterproxymodel.h
        src/filters/remotequery.h
        src/gui/browserWidgets/authoreditor.h
        src/gui/browserWidgets/colormenu.h
        src/gui/browserWidgets/dateeditor.h
        src/gui/browserWidgets/datetimeeditor.h
        src/gui/browserWidgets/editorbuttonbar.h
        src/gui/browserWidgets/expandbutton.h
        src/gui/browserWidgets/fontnamecombobox.h
        src/gui/browserWidgets/fontsizecombobox.h
        src/gui/browserWidgets/locationeditor.h
        src/gui/browserWidgets/notebookmenubutton.h
        src/gui/browserWidgets/ntitleeditor.h
        src/gui/browserWidgets/reminderbutton.h
        src/gui/browserWidgets/table/tablepropertiesdialog.h
        src/gui/browserWidgets/tageditor.h
        src/gui/browserWidgets/tageditornewtag.h
        src/gui/browserWidgets/tagviewer.h
        src/gui/browserWidgets/urleditor.h
        src/gui/datedelegate.h
        src/gui/externalbrowse.h
        src/gui/favoritesview.h
        src/gui/favoritesviewdelegate.h
        src/gui/favoritesviewitem.h
        src/gui/findreplace.h
        src/gui/flowlayout.h
        src/gui/imagedelegate.h
        src/gui/lineedit.h
        src/gui/nattributetree.h
        src/gui/nbrowserwindow.h
        src/gui/nmainmenubar.h
        src/gui/nnotebookview.h
        src/gui/nnotebookviewdelegate.h
        src/gui/nnotebookviewitem.h
        src/gui/nsearchview.h
        src/gui/nsearchviewitem.h
        src/gui/ntableview.h
        src/gui/ntableviewheader.h
        src/gui/ntabwidget.h
        src/gui/ntagview.h
        src/gui/ntagviewdelegate.h
        src/gui/ntagviewitem.h
        src/gui/ntrashtree.h
        src/gui/ntrashviewdelegate.h
        src/gui/numberdelegate.h
        src/gui/nwebpage.h
        src/gui/nwebview.h
        src/gui/plugins/pluginfactory.h
        src/gui/plugins/popplergraphicsview.h
        src/gui/plugins/popplerviewer.h
        src/gui/reminderorderdelegate.h
        src/gui/shortcutkeys.h
        src/gui/traymenu.h
        src/gui/treewidgeteditor.h
        src/gui/truefalsedelegate.h
        src/gui/widgetpanel.h
        src/logger/qsdebugoutput.h
        src/logger/qslog.h
        src/logger/qslogdest.h
        src/models/notecache.h
        src/models/notemodel.h
        src/models/ntreemodel.h
        src/oauth/oauthtokenizer.h
        src/hunspell/spellchecker.h
        src/qevercloud/QEverCloud/src/AsyncResult.h
        src/qevercloud/QEverCloud/src/EventLoopFinisher.h
        src/qevercloud/QEverCloud/src/EverCloudException.h
        src/qevercloud/QEverCloud/src/exceptions.h
        src/qevercloud/QEverCloud/src/generated/constants.h
        src/qevercloud/QEverCloud/src/generated/EDAMErrorCode.h
        src/qevercloud/QEverCloud/src/generated/services.h
        src/qevercloud/QEverCloud/src/generated/types.h
        src/qevercloud/QEverCloud/src/generated/types_impl.h
        src/qevercloud/QEverCloud/src/http.h
        src/qevercloud/QEverCloud/src/impl.h
        src/qevercloud/QEverCloud/src/include/QEverCloud.h
        src/qevercloud/QEverCloud/src/include/QEverCloudOAuth.h
        src/qevercloud/QEverCloud/src/oauth.h
        src/qevercloud/QEverCloud/src/Optional.h
        src/qevercloud/QEverCloud/src/public.h
        src/qevercloud/QEverCloud/src/qt4helpers.h
        src/qevercloud/QEverCloud/src/thrift.h
        src/qevercloud/tQEverCloud/src/humbnail.h
        src/reminders/reminderevent.h
        src/reminders/remindermanager.h
        src/settings/accountsmanager.h
        src/settings/colorsettings.h
        src/settings/filemanager.h
        src/settings/startupconfig.h
        src/sql/configstore.h
        src/sql/databaseconnection.h
        src/sql/databaseupgrade.h
        src/sql/datastore.h
        src/sql/favoritesrecord.h
        src/sql/favoritestable.h
        src/sql/filewatchertable.h
        src/sql/linkednotebooktable.h
        src/sql/notebooktable.h
        src/sql/notemetadata.h
        src/sql/notetable.h
        src/sql/nsqlquery.h
        src/sql/resourcetable.h
        src/sql/searchtable.h
        src/sql/sharednotebooktable.h
        src/sql/tagtable.h
        src/sql/usertable.h
        src/html/attachmenticonbuilder.h
        src/html/enmlformatter.h
        src/html/noteformatter.h
        src/html/tagscanner.h
        src/html/thumbnailer.h
        src/threads/browserrunner.h
        src/threads/counterrunner.h
        src/threads/indexrunner.h
        src/threads/syncrunner.h
        src/utilities/crossmemorymapper.h
        src/utilities/debugtool.h
        src/utilities/encrypt.h
        src/utilities/mimereference.h
        src/utilities/noteindexer.h
        src/utilities/nuuid.h
        src/utilities/pixelconverter.h
        src/utilities/NixnoteStringUtils.h
        src/watcher/filewatcher.h
        src/watcher/filewatchermanager.h
        src/xml/batchimport.h
        src/xml/exportdata.h
        src/xml/importdata.h
        src/xml/importenex.h
        src/xml/xmlhighlighter.h
        src/quentier/utility/StringUtils.h
        src/quentier/utility/StringUtils_p.h
        testsrc/tests.h
)

qt5_wrap_cpp(nixnote2_hdr_moc ${nixnote2_hdr})

include_directories (${PROJECT_SOURCE_DIR})
include_directories (${PROJECT_BINARY_DIR})
include_directories(${TIDY_INCLUDE_DIRS})

add_executable(nixnote2 ${nixnote2_src} ${nixnote2_hdr_moc})
add_executable(tests ${nixnote2_src} ${nixnote2_hdr_moc})

target_link_libraries(nixnote2 Qt5::Widgets Qt5::Sql Qt5::Gui Qt5::Network Qt5:WebKit Qt5:WebKitWidgets)
target_link_libraries(tests Qt5::Widgets Qt5::Sql Qt5::Gui Qt5::Network Qt5:WebKit Qt5:WebKitWidgets)
