/**
 * Original work: Copyright (c) 2014 Sergey Skoblikov
 * Modified work: Copyright (c) 2015-2021 Dmitry Ivanov
 *
 * This file is a part of QEverCloud project and is distributed under the terms
 * of MIT license:
 * https://opensource.org/licenses/MIT
 *
 * This file was generated from Evernote Thrift API
 */

#ifndef QEVERCLOUD_GENERATED_TYPES_H
#define QEVERCLOUD_GENERATED_TYPES_H

#include "types/AccountLimits.h"
#include "types/Accounting.h"
#include "types/AuthenticationResult.h"
#include "types/BootstrapInfo.h"
#include "types/BootstrapProfile.h"
#include "types/BootstrapSettings.h"
#include "types/BusinessInvitation.h"
#include "types/BusinessNotebook.h"
#include "types/BusinessUserAttributes.h"
#include "types/BusinessUserInfo.h"
#include "types/CanMoveToContainerRestrictions.h"
#include "types/Contact.h"
#include "types/CreateOrUpdateNotebookSharesResult.h"
#include "types/Data.h"
#include "types/Identity.h"
#include "types/InvitationShareRelationship.h"
#include "types/LazyMap.h"
#include "types/LinkedNotebook.h"
#include "types/ManageNoteSharesError.h"
#include "types/ManageNoteSharesParameters.h"
#include "types/ManageNoteSharesResult.h"
#include "types/ManageNotebookSharesError.h"
#include "types/ManageNotebookSharesParameters.h"
#include "types/ManageNotebookSharesResult.h"
#include "types/MemberShareRelationship.h"
#include "types/Note.h"
#include "types/NoteAttributes.h"
#include "types/NoteCollectionCounts.h"
#include "types/NoteEmailParameters.h"
#include "types/NoteFilter.h"
#include "types/NoteInvitationShareRelationship.h"
#include "types/NoteLimits.h"
#include "types/NoteList.h"
#include "types/NoteMemberShareRelationship.h"
#include "types/NoteMetadata.h"
#include "types/NoteRestrictions.h"
#include "types/NoteResultSpec.h"
#include "types/NoteShareRelationshipRestrictions.h"
#include "types/NoteShareRelationships.h"
#include "types/NoteVersionId.h"
#include "types/Notebook.h"
#include "types/NotebookDescriptor.h"
#include "types/NotebookRecipientSettings.h"
#include "types/NotebookRestrictions.h"
#include "types/NotebookShareTemplate.h"
#include "types/NotesMetadataList.h"
#include "types/NotesMetadataResultSpec.h"
#include "types/PublicUserInfo.h"
#include "types/Publishing.h"
#include "types/RelatedContent.h"
#include "types/RelatedContentImage.h"
#include "types/RelatedQuery.h"
#include "types/RelatedResult.h"
#include "types/RelatedResultSpec.h"
#include "types/Resource.h"
#include "types/ResourceAttributes.h"
#include "types/SavedSearch.h"
#include "types/SavedSearchScope.h"
#include "types/ShareRelationshipRestrictions.h"
#include "types/ShareRelationships.h"
#include "types/SharedNote.h"
#include "types/SharedNoteTemplate.h"
#include "types/SharedNotebook.h"
#include "types/SharedNotebookRecipientSettings.h"
#include "types/SyncChunk.h"
#include "types/SyncChunkFilter.h"
#include "types/SyncState.h"
#include "types/Tag.h"
#include "types/UpdateNoteIfUsnMatchesResult.h"
#include "types/User.h"
#include "types/UserAttributes.h"
#include "types/UserIdentity.h"
#include "types/UserProfile.h"
#include "types/UserUrls.h"

#include "exceptions/EDAMInvalidContactsException.h"
#include "exceptions/EDAMNotFoundException.h"
#include "exceptions/EDAMSystemException.h"
#include "exceptions/EDAMUserException.h"

#endif // QEVERCLOUD_GENERATED_TYPES_H
