/**
 * Original work: Copyright (c) 2014 Sergey Skoblikov
 * Modified work: Copyright (c) 2015-2025 Dmitry Ivanov
 *
 * This file is a part of QEverCloud project and is distributed under the terms
 * of MIT license:
 * https://opensource.org/licenses/MIT
 *
 * This file was generated from Evernote Thrift API
 */

#ifndef QEVERCLOUD_GENERATED_TYPES_ALL_H
#define QEVERCLOUD_GENERATED_TYPES_ALL_H

#include "AccountLimits.h"
#include "Accounting.h"
#include "AuthenticationResult.h"
#include "BootstrapInfo.h"
#include "BootstrapProfile.h"
#include "BootstrapSettings.h"
#include "BusinessInvitation.h"
#include "BusinessNotebook.h"
#include "BusinessUserAttributes.h"
#include "BusinessUserInfo.h"
#include "CanMoveToContainerRestrictions.h"
#include "Contact.h"
#include "CreateOrUpdateNotebookSharesResult.h"
#include "Data.h"
#include "Identity.h"
#include "InvitationShareRelationship.h"
#include "LazyMap.h"
#include "LinkedNotebook.h"
#include "ManageNoteSharesError.h"
#include "ManageNoteSharesParameters.h"
#include "ManageNoteSharesResult.h"
#include "ManageNotebookSharesError.h"
#include "ManageNotebookSharesParameters.h"
#include "ManageNotebookSharesResult.h"
#include "MemberShareRelationship.h"
#include "Note.h"
#include "NoteAttributes.h"
#include "NoteCollectionCounts.h"
#include "NoteEmailParameters.h"
#include "NoteFilter.h"
#include "NoteInvitationShareRelationship.h"
#include "NoteLimits.h"
#include "NoteList.h"
#include "NoteMemberShareRelationship.h"
#include "NoteMetadata.h"
#include "NoteRestrictions.h"
#include "NoteResultSpec.h"
#include "NoteShareRelationshipRestrictions.h"
#include "NoteShareRelationships.h"
#include "NoteVersionId.h"
#include "Notebook.h"
#include "NotebookDescriptor.h"
#include "NotebookRecipientSettings.h"
#include "NotebookRestrictions.h"
#include "NotebookShareTemplate.h"
#include "NotesMetadataList.h"
#include "NotesMetadataResultSpec.h"
#include "PublicUserInfo.h"
#include "Publishing.h"
#include "RelatedContent.h"
#include "RelatedContentImage.h"
#include "RelatedQuery.h"
#include "RelatedResult.h"
#include "RelatedResultSpec.h"
#include "Resource.h"
#include "ResourceAttributes.h"
#include "SavedSearch.h"
#include "SavedSearchScope.h"
#include "ShareRelationshipRestrictions.h"
#include "ShareRelationships.h"
#include "SharedNote.h"
#include "SharedNoteTemplate.h"
#include "SharedNotebook.h"
#include "SharedNotebookRecipientSettings.h"
#include "SyncChunk.h"
#include "SyncChunkFilter.h"
#include "SyncState.h"
#include "Tag.h"
#include "TypeAliases.h"
#include "UpdateNoteIfUsnMatchesResult.h"
#include "User.h"
#include "UserAttributes.h"
#include "UserIdentity.h"
#include "UserProfile.h"
#include "UserUrls.h"

#endif // QEVERCLOUD_GENERATED_TYPES_ALL_H
